svg = d3.select('body')
    .append('svg')
    .attr('width', 400)
    .attr('height', 400)
    .style('background', '#999')

svg.append('rect')
    .attr('width', 300)
    .attr('height', 300)
    .attr('x', 50)
    .attr('y', 50)
    .style('fill', 'red')
    .style('stroke', 'black')
    .style('stroke-width', '3')

svg.append('circle')
    .attr('cx', 200)
    .attr('cy', 200)
    .attr('r', 100)
    .style('fill', 'yellow')
    .style('stroke', 'black')
    .style('stroke-width', 3)